# - hosts: demo
#  tasks:
#   - name: "Ping"
#     ping:
#
#- name: "ping group nginx"
#  hosts: nginx
#  tasks:
#  - name: "ping"
#    ping:

- name: install lab3 stuff
  hosts: virtualmachines
  tasks:
    - name: install wget on both vms
      become: yes
      package:
        name: wget
        state: present

    - name: install unzip on vm01
      become: yes
      package:
        name: unzip
        state: present
      when: ansible_host == '35.177.38.124'

    - name: install nginx on vm02
      become: yes
      package:
        name: nginx
        state: present
      when: ansible_host == '13.41.203.226'

    - name: uninstall unzip on both vms2
      become: yes
      apt:
        name: unzip
        state: absent


# task 2
    - name: Install nginx on vm01
      become: yes
      package:
        name: nginx
        state: present
      when: ansible_host == '35.177.38.124'
      register: nginx_install

    - name: Change default nginx html
      become: yes
      copy:
        src: /var/www/html/index.nginx-debian.html
        dest: /var/www/html/index.nginx-debian.html
      when: ansible_host == '35.177.38.124'

    - name: Restart nginx
      become: yes
      service:
        name: nginx
        state: restarted
      when: ansible_host == '35.177.38.124'

    - name: Print out nginx install JSON object
      become: yes
      debug:
        var: nginx_install
      when: ansible_host == '35.177.38.124'
      register: nginx_install

    - name: Install prerequisites for Docker repo
      become: yes
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        update_cache: true
      when: ansible_host == '35.177.38.124'


    - name: Add Docker GPG key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
      when: ansible_host == '35.177.38.124'

    - name: Add Docker APT repository
      become: yes
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
      when: ansible_host == '35.177.38.124'

    - name: Install Docker CE
      become: yes
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
      when: ansible_host == '35.177.38.124'

    - name: Install prerequisites for docker-compose
      become: yes
      apt:
        name:
          - python3-pip
          - python3-setuptools
          - virtualenv
      when: ansible_host == '35.177.38.124'

    - name: Install docker-compose
      become: yes
      pip:
        name: docker-compose
      when: ansible_host == '35.177.38.124'

    - name: Ensure Docker is started
      become: yes
      service:
        name: docker
        state: started
      when: ansible_host == '35.177.38.124'

    - name: Install Docker on vm02
      become: yes
      shell: curl https://get.docker.com | sudo bash
      when: ansible_host == '13.41.203.226'
